### ISSUE TITLE
How to define RAW numbers initial values

### ISSUE THREAD

**Issue by MyVanitar** [taburyak/STM32-touchscreen-XPT2046-HAL-SPI#2]
Hello,

I want to define the upper-left corner as (0, 0) coordinate of my TFT screen. like below:

![2021-04-27_12-22-34](https://user-images.githubusercontent.com/18719591/116206265-dd308200-a753-11eb-846b-c784f5a4b26c.jpg)

What should I do and how to define the initial values for the RAW X and RAW Y?

**Comment by taburyak** [comment]
// Uncomment this line to calibrate touchscreen:
    //printf("raw_x = %d, raw_y = %d\r\n", (int) raw_x, (int) raw_y);
uncommented the line.  press the touch 0,0 and 320,240 coordinate.  in the series monitor watch the value of raw

**Comment by MyVanitar** [comment]
That's right, but I mean these value in the header file, what should I insert for the **first test** (initial values of RAW_X and RAW_Y)
```
#define XPT2046_MIN_RAW_X 3400
#define XPT2046_MAX_RAW_X 29000
#define XPT2046_MIN_RAW_Y 3300
#define XPT2046_MAX_RAW_Y 30000
```

**Comment by taburyak** [comment]
these are the initial values

**Comment by MyVanitar** [comment]
Yes, but how do you define these values?
